[
    {"universityName":"Abubakar Tafawa Balewa University","websiteLinks":"https://www.atbu.edu.ng","state":"Bauchi"},
    {"universityName":"Ahmadu Bello University","websiteLinks":"https://www.abu.edu.ng","state":"Zaria"},
    {"universityName":"Bayero University","websiteLinks":"https://www.buk.edu.ng","state":"Kano"},
    {"universityName":"Federal University Gashua","websiteLinks":"https://www.fugashua.edu.ng","state":"Yobe"},
    {"universityName":"Federal University of Petroleum Resources","websiteLinks":"https://www.fupre.edu.ng","state":"Effurun"},
    {"universityName":"Federal University of Technology","websiteLinks":"https://www.futa.edu.ng","state":"Akure"},
    {"universityName":"Federal University of Technology","websiteLinks":"https://www.futminna.edu.ng","state":"Minna"},
    {"universityName":"Federal University of Technology","websiteLinks":"https://www.futo.edu.ng","state":"Owerri"},
    {"universityName":"Federal University","websiteLinks":"https://www.fud.edu.ng/","state":"Jigawa State"},
    {"universityName":"Federal University","websiteLinks":"https://www.fudutsinma.edu.ng","state":"Katsina"},
    {"universityName":"Federal University","websiteLinks":"https://www.fukashere.edu.ng","state":"Gombe State"},
    {"universityName":"Federal University","websiteLinks":"https://www.fulafia.edu.ng","state":"Nasarawa State"},
    {"universityName":"Federal University","websiteLinks":"https://www.fulokoja.edu.ng","state":"Kogi State"},
    {"universityName":"Alex Ekwueme University","websiteLinks":"https://www.funai.edu.ng","state":"Ebonyi State"},
    {"universityName":"Federal University","websiteLinks":"https://www.fuotuoke.edu.ng/","state":"Bayelsa"},
    {"universityName":"Federal University","websiteLinks":"https://www.fuoye.edu.ng/","state":"Ekiti State"},
    {"universityName":"Federal University","websiteLinks":"https://www.fuwukari.edu.ng/","state":"Taraba State"},
    {"universityName":"Federal University","websiteLinks":"https://www.fubk.edu.ng","state":"Birnin Kebbi"},
    {"universityName":"Federal University","websiteLinks":"https://www.fugusau.edu.ng","state":"Gusau Zamfara"},
    {"universityName":"Michael Okpara University of Agricultural Umudike","websiteLinks":"https://www.mouau.edu.ng","state":""},
    {"universityName":"Modibbo Adama University of Technology","websiteLinks":"https://www.mautech.edu.ng","state":"Yola"},
    {"universityName":"National Open University of Nigeria","websiteLinks":"https://www.nou.edu.ng","state":"Abuja"},
    {"universityName":"Nigeria Police Academy Wudil","websiteLinks":"https://polac.edu.ng/","state":""},
    {"universityName":"Nigerian Defence Academy Kaduna","websiteLinks":"https://www.nda.edu.ng","state":""},
    {"universityName":"Nnamdi Azikiwe University","websiteLinks":"https://www.unizik.edu.ng","state":"Awka"},
    {"universityName":"Obafemi Awolowo University","websiteLinks":"https://www.oauife.edu.ng","state":"Ile-Ife"},
    {"universityName":"University of Abuja","websiteLinks":"https://www.uniabuja.edu.ng","state":"Gwagwalada"},
    {"universityName":"Federal University of Agriculture","websiteLinks":"https://www.unaab.edu.ng","state":"Abeokuta"},
    {"universityName":"Joseph Sarwuan Tarka University","websiteLinks":"https://www.uam.edu.ng","state":"Makurdi"},
    {"universityName":"University of Benin","websiteLinks":"https://www.uniben.edu.ng","state":""},
    {"universityName":"University of Calabar","websiteLinks":"https://www.unical.edu.ng","state":""},
    {"universityName":"University of Ibadan","websiteLinks":"https://www.ui.edu.ng","state":""},
    {"universityName":"University of Ilorin","websiteLinks":"https://www.unilorin.edu.ng","state":""},
    {"universityName":"University of Jos","websiteLinks":"https://www.unijos.edu.ng","state":""},
    {"universityName":"University of Lagos","websiteLinks":"https://www.unilag.edu.ng","state":""},
    {"universityName":"University of Maiduguri","websiteLinks":"https://www.unimaid.edu.ng","state":""},
    {"universityName":"University of Nigeria","websiteLinks":"https://www.unn.edu.ng","state":"Nsukka"},
    {"universityName":"University of Port-Harcourt","websiteLinks":"https://www.uniport.edu.ng","state":""},
    {"universityName":"University of Uyo","websiteLinks":"https://www.uniuyo.edu.ng","state":""},
    {"universityName":"Usumanu Danfodiyo University","websiteLinks":"https://www.udusok.edu.ng","state":""},
    {"universityName":"Nigerian Maritime University Okerenkoko","websiteLinks":"https://www.nmu.edu.ng","state":"Delta State"},
    {"universityName":"Air Force Institute of Technology","websiteLinks":"https://afit.edu.ng","state":"Kaduna"},
    {"universityName":"Nigerian Army University Biu","websiteLinks":"https://naub.edu.ng/","state":""},
    {"universityName":"Federal University of Health Sciences","websiteLinks":"","state":"Benue State"},
    {"universityName":"Federal University of Agriculture","websiteLinks":"","state":"Kebbi State"},
    {"universityName":"Federal University of Technology","websiteLinks":"","state":"Jigawa State"},
    {"universityName":"Federal University of Technology","websiteLinks":"","state":"Akwa Ibom State"},
    {"universityName":"Federal University of Health Sciences","websiteLinks":"","state":"Bauchi State"},
    {"universityName":"Federal University of Health Sciences","websiteLinks":"","state":"Osun State"},
    {"universityName":"David Nweze Umahi Federal University of Medical Sciences","websiteLinks":"https://kdums.edu.ng/","state":"Uburu"},
    {"universityName":"Admiralty University Ibusa","websiteLinks":"https://adun.edu.ng","state":"Delta State"},
    {"universityName":"Federal University of Transportation Daura","websiteLinks":"https://www.futd.edu.ng/","state":"Katsina"},
    {"universityName":"African Aviation and Aerospace University","websiteLinks":"https://aaau.edu.ng/","state":""},
    {"universityName":"National University of Science and Technology","websiteLinks":"","state":"Abuja"},
    {"universityName":"Federal University of Agriculture Bassam-Biri","websiteLinks":"","state":"Bayelsa"},
    {"universityName":"Federal University of Health Sciences Kwale","websiteLinks":"","state":"Delta State"},
    {"universityName":"Federal University of Health Sciences","websiteLinks":"","state":"Katsina"},
    {"universityName":"Federal University of Agriculture","websiteLinks":"","state":"Mubi"},
    {"universityName":"Federal University of Education","websiteLinks":"","state":"Kaduna State"},
    {"universityName":"Alvan Ikoku Federal University of Education","websiteLinks":"","state":"Imo State"},
    {"universityName":"Yusuf Maitama Sule Federal University of Education","websiteLinks":"","state":"Kano"},
    {"universityName":"Adeyemi Federal University of Education","websiteLinks":"","state":"Ondo"},
    {"universityName":"Federal University of Allied Health Sciences","websiteLinks":"","state":"Enugu"},
    {"universityName":"Federal University of Medicine and Medical Sciences","websiteLinks":"https://fummsa.net","state":"Abeokuta"},
    {"universityName":"Federal University of Education Pankshin","websiteLinks":"","state":"Plateau State"},
    {"universityName":"Federal University of Education Kontagora","websiteLinks":"","state":"Niger State"},
    {"universityName":"University of Maritime Studies","websiteLinks":"","state":"Akwa Ibom State"},
    {"universityName":"Federal University of Environment and Technology","websiteLinks":"","state":"Rivers State"},
    {"universityName":"Federal University of Applied Sciences","websiteLinks":"","state":"Kaduna State"},
    {"universityName":"Tai Solarin Federal University of Education","websiteLinks":"","state":"Ijebu Ode"},
    {"universityName":"Federal University of Agriculture and Developmental Studies","websiteLinks":"","state":"Osun State"},
    {"universityName":"Federal University of Technology and Environmental Studies","websiteLinks":"","state":"Ekiti State"},
    {"universityName":"Federal University of Agriculture and Technology Okeho","websiteLinks":"","state":"Oyo State"},
    {"universityName":"Federal University of Health Science and Technology","websiteLinks":"","state":"Tsafe"}
]

/* 
CREATE TABLE add_university(
      
      add_university_id int PRIMARY KEY AUTO_INCREMENT NOT NULL,
      university_name VARCHAR(200) NOT NULL,
      state_of_location VARCHAR(200) ,
      local_government VARCHAR(200) ,
      foreign_or_local VARCHAR(200) ,
        institutionCategory VARCHAR(200) ,
        phone_number VARCHAR(200) ,
        email VARCHAR(200) ,
        website VARCHAR(200) ,
        ins_address VARCHAR(200) ,
        accreditation VARCHAR(200) ,
        courses_offered TEXT ,
        about_institution TEXT ,
        other_institution TEXT,
      token VARCHAR(200) ,
      createdAtTime VARCHAR(100),
      createdAtDate VARCHAR(100)
      
);
 */


